name: deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Use gcloud CLI
        run: gcloud info
      - name: Install packages, build frontend, and rename directories
        run: cd react && npm install && npm run build && mv build html && cd .. && mv php psignapi
      - name: Copy frontend files
        run: gcloud compute scp --recurse react/html root@proton-sign-deployed:/var/www/ --zone "us-west2-a"
      - name: Copy backend files
        run: gcloud compute scp --recurse psignapi root@proton-sign-deployed:/var/www/html/ --zone "us-west2-a"
